language: node_js
node_js:
  - "6.10.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python3-pip
cache:
  directories:
    - node_modules
before_script:
  - pwd
  - npm install
script:
  - npm run build
before_deploy:
  - pip install --upgrade --user awscli
deploy:
  provider: s3
  access_key_id: $HACKILLINOIS_ACCESS_KEY_ID
  secret_access_key: $HACKILLINOIS_SECRET_ACCESS_KEY
  bucket: $HACKILLINOIS_BUCKET_NAME
  skip_cleanup: true
  local_dir: public
after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths '/*'
  - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_IDENTIFIER/purge_cache" \
     -H "X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL" \
     -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'
